image: node:12-alpine

variables:
  GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${CI_PROJECT_PATH}"

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules/

stages:
  - Lint
  - Test
  - Publish


lint:
  stage: Lint
  before_script:
    - yarn
  script:
    - yarn lint


test:
  stage: Test
  before_script:
    - yarn
  script:
    - yarn test


publish:
  stage: Publish
  before_script:
    - yarn
  script:
    - echo 'TODO'
  only:
    - master
