image: node:12-alpine

stages:
  - Lint
  - Test
  - Publish

lint:
  stage: Lint
  cache:
    paths:
    - node_modules/
  before_script:
    - yarn
  script:
    - yarn lint

test:
  stage: Test
  cache:
    paths:
    - node_modules/
  before_script:
    - yarn
  script:
    - yarn test

publish:
  stage: Publish
  before_script:
    - yarn
  script:
    - echo 'TODO'
  only:
    - master
